name: Build and release

on:
  release:
    types: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        server-id: github
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup workspace
      run: mkdir artifacts
    - name: Build with Maven
      run: mvn -B release --file pom.xml
          
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
